### ISSUE TITLE
No module named 'ufw'

### ISSUE THREAD

**Issue by bitnom** [5tingray/pyufw#1]
Python 3.8.1

`import pyufw as ufw`

produces: **ModuleNotFoundError: No module named 'ufw'**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/project-tfrSiZZq/lib/python3.8/site-packages/pyufw/__init__.py", line 1, in <module>
    from .pyufw import *
  File "/home/user/.local/share/virtualenvs/project-tfrSiZZq/lib/python3.8/site-packages/pyufw/pyufw.py", line 4, in <module>
    import ufw.frontend
```

**Comment by 5tingray** [comment]
Have you tried installing the ufw or python-ufw packages from your package manager?

**Comment by bitnom** [comment]
Not having python-ufw was the problem. This means we can't use things like pipenv though. Why isn't that package also in pypi?

**Comment by 5tingray** [comment]
I'm not sure why it's not available in PyPi... Might be worth suggesting it to jamie@canonical.com who maintains it.

UFW is written in pure python and I believe you can pull packages from git repos with pipenv.

https://git.launchpad.net/ufw

One option from my end could be to include the UFW source in my package but initially I didn't want to be responsible for updating a UFW fork. But that's a decision I could potentially go back on...

Hope this helps.

**Comment by bitnom** [comment]
Thx
